### ISSUE TITLE
flesh out process.storm_gage_height to resample gage height to timesteps

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/hurricane-maria#24]
this is a placeholder function (that does nothing) in #23 

We'll need to depend on timestamps and resample the gage height data to those steps, then save.

**Comment by dblodgett-usgs** [comment]
I used logic from Irma for the most part. I'm cuonfused by the filter here though: https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/process/process.timestep_discharge.R#L14 Theoretically that returns stuff outside the range of the precip data?

**Comment by jread-usgs** [comment]
yes, in case the exact hourly match (for interpolation) is missing for the first and last timestep, it extends beyond that, and then hourly interp is used.
