### ISSUE TITLE
clip precip cells that don't overlap w/ islands

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/hurricane-maria#30]
unnecessary things in the DOM that aren't used. Right now the render skips it because of clipPath

**Comment by jread-usgs** [comment]
would need an island buffer to cover those centroids that aren't contained, but do have part of a pixel on an island

**Comment by dblodgett-usgs** [comment]
Or a precip cell to intersect with the unbuffered island that tells us to keep certain IDs.

**Comment by jread-usgs** [comment]
either way. let me know if you are going to turn that precip `sp` object into polygon (from points). It will change a little of what I am doing, but probably make it better if you can get that cell rotation in there.

**Comment by dblodgett-usgs** [comment]
No, it'll stay a point collection but I can cull out points we don't need.

**Comment by jread-usgs** [comment]
how if not buffer?

**Comment by dblodgett-usgs** [comment]
There'll be a cell geometry and a point geometry with the same id. I'll do the culling with the cell geometry then drop the IDs that we don't need from the point version. It's what I did in Irma.

**Comment by jread-usgs** [comment]
ok, but if you are going through the process of getting a box made for the cell that has the proper rotation, why not just use it for the render polygon (so I don't have to build one from the `circle`),

**Comment by dblodgett-usgs** [comment]
Decided to hold off on this as it's a nice to have.
