### ISSUE TITLE
are we including Isla de Mona?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/hurricane-maria#33]
![image](https://user-images.githubusercontent.com/2349007/30647823-192e9b40-9de2-11e7-8e08-2507b78679b3.png)

Seems like we are missing it. Do we have precip for it? the poly for the island?

**Comment by ldecicco-USGS** [comment]
For what it's worth, there's no buildings or people that live on Mona (other than maybe 1 shed to hold some tools to maintain a trail). It could be nice to include to center PR a bit on the map, but I don't think anyone would be too upset if it wasn't included.

**Comment by dblodgett-usgs** [comment]
So... no I don't think we are. Close?

**Comment by jread-usgs** [comment]
yes, we do have precip for it: 
![image](https://user-images.githubusercontent.com/2349007/30748606-6ae1f172-9f76-11e7-8558-05580e69de27.png)

**Comment by jread-usgs** [comment]
(but are the data accurate?)
