### ISSUE TITLE
NWS flood stage gages fetch and process.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/hurricane-maria#5]
Shapefile of gages is available here: https://water.weather.gov/ahps2/download.php?wfo=sju

It has flood stage for gages. It does NOT have NWIS gage IDs in it. Crosswalk is available here: http://www.nws.noaa.gov/oh/hads/USGS/PR_USGS-HADS_SITES.txt

See this: https://github.com/USGS-VIZLAB/hurricane-irma/blob/master/scripts/fetch/fetch.nws_conversion.R for a conversion that's already been done.

Fetch and open shapefile, save as spatialPointsDataFrame with flood stage in it. 

Use fetch.nws_conversion.R as it stands but for Puerto Rico.

One more fetch or a process to combine these two fetches together and save spatialPolygonsDataFrame with NWIS ID, NWS ID, and flood stage in it would be nice to include other stuff in the NWS shape file like name, waterbody name, and NWS URL.

**Comment by ldecicco-USGS** [comment]
Still to do:

 - [ ] Convert sites data frame to spatialPointsDataFrame
 - [ ] Get NWIS gage height data
 - [ ]  Check if the shapefile @dblodgett-usgs links above has more flood information than the XML pages we're scrapping

**Comment by dblodgett-usgs** [comment]
![screen shot 2017-09-19 at 5 47 18 pm](https://user-images.githubusercontent.com/1492803/30619001-9fbe69b8-9d62-11e7-852b-2435cb1b74cd.png)

**Comment by jread-usgs** [comment]
Looks like 1 and 2 of the above is done, but I don't think we have cross-ref'd to the shp

**Comment by dblodgett-usgs** [comment]
I think this is done, except that the scraping is super duper slow compared to what we could do with the shapefile version... no biggie though. We can move on.

**Comment by dblodgett-usgs** [comment]
We can open a new issue to pull in the shapefile version and additional information later on if we need it.
