### ISSUE TITLE
Quicky map starting point.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/hurricane-maria#6]
See this: https://gist.github.com/dblodgett-usgs/de88c44598ac4a96e4274bc5f33d1f1e#file-puerto_rico_radar_precip-r-L99 It's a decent place to start.

**Comment by dblodgett-usgs** [comment]
Sounds like @jread-usgs has something from Irma for this too.

**Comment by jread-usgs** [comment]
done in #9
