### ISSUE TITLE
change order of rivers to have the bottom ones peak first

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/hurricane-maria#63]
instead of `arrange(desc(coords.x1)) `, use `arrange(coords.x1)` ?

currently, this feels like the rivers on the top (the eastern most ones) should be the ones on the bottom:

![image](https://user-images.githubusercontent.com/2349007/30673316-b5c1eb92-9e37-11e7-848b-30c4ae959f19.png)

**Comment by dblodgett-usgs** [comment]
Maybe I switched it because of negative longitude going the other way? Didn't mean to, let's switch back.

**Comment by dblodgett-usgs** [comment]
fixed with latest in #62
