### ISSUE TITLE
"reveal" boxes not working. Related to svginject?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/hurricane-maria#67]
For some reason, the IDs in the `<defs/>` part of the svg are getting `-0` appended to them. 

In the page, they appear like this:
![image](https://user-images.githubusercontent.com/2349007/30692666-1c73829c-9e92-11e7-9272-e860715fdb3d.png)

vs in the svg that is getting injected, they look like this:
```xml
<defs>
    <clipPath id="flood-clip-50148890">
      <rect width="100%" height="7.74" y="0"/>
    </clipPath>
    <clipPath id="flood-clip-50138000">
      <rect width="100%" height="9.35" y="0"/>
    </clipPath>
    <clipPath id="flood-clip-50147800">
      <rect width="100%" height="6.93" y="0"/>
    </clipPath>
    <clipPath id="flood-clip-50136400">
      <rect width="100%" height="7.38" y="0"/>
    </clipPath>
    <clipPath id="flood-clip-50144000">
      <rect width="100%" height="10.84" y="0"/>
    </clipPath>
    <clipPath id="flood-clip-50024950">
      <rect width="100%" height="7.81" y="0"/>
    </clipPath>
</defs>
```

**Comment by jiwalker-usgs** [comment]
Yeah, this is the inject doing this https://github.com/iconic/SVGInjector/blob/master/svg-injector.js#L284

**Comment by jread-usgs** [comment]
any possible fix for this? Do you know why they would do that?

**Comment by jiwalker-usgs** [comment]
it also changes the references to it, so it should be fine, I'm not exactly seeing where the problem arises

**Comment by jread-usgs** [comment]
but the references to clips and masks are prefixed w/ `#`, and they aren't being altered in the same way on inject

**Comment by jread-usgs** [comment]
the reference does not change w/ inject:

![image](https://user-images.githubusercontent.com/2349007/30708369-3a976572-9ec4-11e7-91b5-2bb83e7ee6af.png)

**Comment by jiwalker-usgs** [comment]
ok, I see the issue now, seems like a bug since the other ones are changing.

**Comment by jread-usgs** [comment]
yeah, the clipPath ones are fine

**Comment by jiwalker-usgs** [comment]
would it be possible to move the mask attribute outside of style?

**Comment by jread-usgs** [comment]
ha! duh! forgot that was possible. I will do that. I bet it works. great idea

**Comment by jread-usgs** [comment]
worked around the bug in #77
