### ISSUE TITLE
Figure goes black when switching modes.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-VIZLAB/hurricane-maria#71]
Minor, but for whatever reason switching modes (desktop to mobile or vice versa) makes all but the precip scale legend go black. 

![screen shot 2017-09-21 at 8 54 05 am](https://user-images.githubusercontent.com/1492803/30699485-7c9d3984-9eaa-11e7-9947-6cf3bda89b95.png)

**Comment by mwernimont** [comment]
This seems to be fixed
